version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80" # Mapeia a porta 80 do container para a 3000 do host
    volumes:
      - ./dist:/usr/share/nginx/html
    container_name: meu-portfolio
